import React from "react";

import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} `}>
        <main className="bg-cyan-100 h-screen flex items-center justify-center">
          <div className="max-w-screen-md m-auto flex-1 max-h-96 h-full">
            <div className="bg-white rounded-3xl shadow-lg w-full h-full p-10">
              {children}
            </div>
          </div>
        </main>
      </body>
    </html>
  );
}
