import React from "react";

import "./globals.css";
import type { Metadata } from "next";
import { Space_Mono } from "next/font/google";

const spaceMono = Space_Mono({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${spaceMono.className} `}>
        <main className="bg-cyan-100 h-screen flex items-center justify-center">
          <div className="mx-auto flex max-w-screen-md flex-1 flex-col px-4">
            <div className="grid w-full flex-1 rounded-3xl bg-white p-8 shadow-lg">
              {children}
            </div>
          </div>
        </main>
      </body>
    </html>
  );
}
